### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/WikiBuilder#1]
- [x] Load Templates
- [x] Load Json files
- [x] Parse Json Files
- [x] Inject json into templates
- [ ] Load Images
- [ ] Output images only if used
- [x] Output new html files
- [ ] Added build server support
- [ ] Add Editor GUI
- [ ] Add .git support to editor for syning
- [ ] Add list of wikis to edit in editor
- [ ] Add real time view of wiki while editing
